config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
  get 'add', to: 'posts#add', as: 'add_post'
  post 'add', to: 'posts#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    include CarrierWave::MiniMagick

    mount_uploader :image, ImageUploader
    belongs_to :category
    validates :title, presence: true
    validates :image, presence: true
    # validates :category_id, inclusion: {in: Category.all.pluck(:id)}
    validate :check_image_dimensions

    # ------------------------------------------------------------------
    # Public Instance Methods
    # ------------------------------------------------------------------
    def check_image_dimensions
        unless geometry.nil?
            if geometry[:width] < 50 || geometry[:height] < 50 || geometry[:width] > 1000 || geometry[:height] > 1000
                errors.add(:image, ' must be between 50x50 and 1000x1000')
            end
        end

        # for debug
        p '--------------------------------------------------'
        p geometry
        p '--------------------------------------------------'
    end

    def geometry
        @geometry ||= _geometry
    end

    private
    # ------------------------------------------------------------------
    # Private Instance Methods
    # ------------------------------------------------------------------
    def _geometry
        if image.current_path
            img = MiniMagick::Image.open(image.current_path)
            if img
                { width: img[:width], height: img[:height] }
            end
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    layout "application"

    def index
        @posts = Post.all
    end
    
    def add
        @post = Post.new
    end

    def create
        post = Post.new post_params
        post.save!
        redirect_to root_path and return
    end

    private
    def post_params
      params.require(:post).permit(:title, :image, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rorphoto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/add.html.erb
<h1>画像投稿</h1>
<%= form_for @post, url: add_post_path do |f| %>
<div>
    <%= f.text_field :title, placeholder: "タイトル" %>
</div>
<div>
<%= f.file_field :image %>
</div>
<div>
<%= f.select :category_id, options_from_collection_for_select(Category.all, 'id', 'name'), :include_blank => 'Please Select' %>
</div>
<div>
<%= f.submit "投稿" %>
</div>
<% end %>

app/views/posts/index.html.erb
<%= link_to '新規投稿', add_post_path %>
<h1>投稿一覧</h1>
<ul>
<% @posts.each do |post| %>
<li>
<p><%= post.title %></p>
<%= image_tag post.image.thumb.url %>
</li>
<% end %>
</ul>